"""Finite-element solution of the electrostatic Laplace equation.

This module solves

    div(grad(phi)) = 0

inside a simple 3D box.

The solver computes a normalized static base potential for electrode patches
held at +1 V and -1 V.  Because Laplace's equation is linear, particle dynamics
can later multiply the resulting base electric field by any voltage waveform.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from skfem import Basis, ElementTetP1, MeshTet, asm, condense, solve
from skfem.models.poisson import laplace

from config import DEFAULT_CONFIG, SimulationConfig


BASE_FIELD_VOLTAGE = 1.0


@dataclass
class FemResult:
    """Container for the FEM solution and grid data used for interpolation."""

    mesh: MeshTet
    basis: Basis
    base_voltage: float
    potential: np.ndarray
    x_grid: np.ndarray
    y_grid: np.ndarray
    z_grid: np.ndarray
    potential_grid: np.ndarray
    electric_field_grid: np.ndarray


def make_coordinate_grid(config: SimulationConfig) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return node coordinates for a box centered at the origin."""

    lx, ly, lz = config.domain_size
    nx, ny, nz = config.mesh_cells

    if min(nx, ny, nz) < 2:
        raise ValueError("Each mesh_cells entry should be at least 2.")

    x_grid = np.linspace(-0.5 * lx, 0.5 * lx, nx + 1)
    y_grid = np.linspace(-0.5 * ly, 0.5 * ly, ny + 1)
    z_grid = np.linspace(-0.5 * lz, 0.5 * lz, nz + 1)
    return x_grid, y_grid, z_grid


def boundary_potential(
    points: np.ndarray,
    config: SimulationConfig,
    base_voltage: float = BASE_FIELD_VOLTAGE,
) -> np.ndarray:
    """Evaluate the simple quadrupole-like Dirichlet boundary condition.

    Parameters
    ----------
    points:
        Array with shape (3, n_points).  Rows are x, y, z coordinates.
    config:
        Simulation settings.

    Returns
    -------
    numpy.ndarray
        Normalized potential values in volts at the supplied points.

    Notes
    -----
    This is not a real electrode model.  It is a clean placeholder:

    * patch on x = +Lx/2 and x = -Lx/2: +1 V
    * patch on y = +Ly/2 and y = -Ly/2: -1 V
    * all other outer boundaries: 0 V

    The patches are kept away from edges by ``electrode_patch_fraction`` so
    there are no ambiguous edge nodes with two different voltages.

    This base solution is later scaled in ``particle_dynamics.py``.  That keeps
    the FEM solve independent of the chosen DC or RF waveform.
    """

    x, y, z = points
    lx, ly, lz = config.domain_size
    hx, hy, hz = 0.5 * lx, 0.5 * ly, 0.5 * lz

    # Coordinate comparisons need a small tolerance because coordinates are
    # floating-point values generated by np.linspace.
    tol = 1.0e-12 * max(config.domain_size)
    patch_y = 0.5 * config.electrode_patch_fraction * ly
    patch_x = 0.5 * config.electrode_patch_fraction * lx
    patch_z = 0.5 * config.electrode_patch_fraction * lz

    on_x_wall = np.isclose(np.abs(x), hx, atol=tol)
    on_y_wall = np.isclose(np.abs(y), hy, atol=tol)

    in_x_patch = on_x_wall & (np.abs(y) <= patch_y) & (np.abs(z) <= patch_z)
    in_y_patch = on_y_wall & (np.abs(x) <= patch_x) & (np.abs(z) <= patch_z)

    values = np.zeros(points.shape[1], dtype=float)
    values[in_x_patch] = base_voltage
    values[in_y_patch] = -base_voltage
    return values


def nodal_values_to_grid(
    mesh: MeshTet,
    nodal_values: np.ndarray,
    x_grid: np.ndarray,
    y_grid: np.ndarray,
    z_grid: np.ndarray,
) -> np.ndarray:
    """Place nodal values from the FEM mesh onto the structured grid.

    ``MeshTet.init_tensor`` creates tetrahedra from a structured set of grid
    points.  Keeping this grid representation makes plotting and interpolation
    easier for the first prototype.
    """

    ix = _nearest_grid_indices(x_grid, mesh.p[0])
    iy = _nearest_grid_indices(y_grid, mesh.p[1])
    iz = _nearest_grid_indices(z_grid, mesh.p[2])

    values_grid = np.full((len(x_grid), len(y_grid), len(z_grid)), np.nan)
    values_grid[ix, iy, iz] = nodal_values

    if np.isnan(values_grid).any():
        raise RuntimeError("Could not map all FEM node values onto the tensor grid.")

    return values_grid


def compute_electric_field_grid(
    potential_grid: np.ndarray,
    x_grid: np.ndarray,
    y_grid: np.ndarray,
    z_grid: np.ndarray,
) -> np.ndarray:
    """Compute the normalized base field E_base = -grad(phi_base).

    For this first structured-mesh prototype, finite differences on the nodal
    potential grid are the most transparent way to obtain a field for plotting
    and interpolation.  For a future unstructured real electrode geometry, this
    should be replaced by element-wise FEM gradients.
    """

    edge_order = 2 if min(potential_grid.shape) >= 3 else 1
    dphi_dx, dphi_dy, dphi_dz = np.gradient(
        potential_grid,
        x_grid,
        y_grid,
        z_grid,
        edge_order=edge_order,
    )

    return -np.stack((dphi_dx, dphi_dy, dphi_dz), axis=-1)


def solve_laplace(config: SimulationConfig = DEFAULT_CONFIG) -> FemResult:
    """Assemble and solve the normalized 3D Laplace problem.

    The boundary patches are fixed at +1 V and -1 V here.  A real static
    voltage or an RF voltage waveform is applied later by multiplying this base
    field, using the linearity of Laplace's equation.
    """

    x_grid, y_grid, z_grid = make_coordinate_grid(config)
    mesh = MeshTet.init_tensor(x_grid, y_grid, z_grid)
    basis = Basis(mesh, ElementTetP1())

    stiffness = asm(laplace, basis)
    rhs = np.zeros(basis.N)

    # P1 elements have one degree of freedom per mesh vertex.  The vector below
    # stores known Dirichlet values at boundary vertices.
    boundary_dofs = basis.get_dofs().all()
    dirichlet_values = np.zeros(basis.N)
    dirichlet_values[boundary_dofs] = boundary_potential(
        mesh.p[:, boundary_dofs],
        config,
        base_voltage=BASE_FIELD_VOLTAGE,
    )

    potential = solve(
        *condense(stiffness, rhs, D=boundary_dofs, x=dirichlet_values)
    )

    potential_grid = nodal_values_to_grid(mesh, potential, x_grid, y_grid, z_grid)
    electric_field_grid = compute_electric_field_grid(
        potential_grid,
        x_grid,
        y_grid,
        z_grid,
    )

    return FemResult(
        mesh=mesh,
        basis=basis,
        base_voltage=BASE_FIELD_VOLTAGE,
        potential=potential,
        x_grid=x_grid,
        y_grid=y_grid,
        z_grid=z_grid,
        potential_grid=potential_grid,
        electric_field_grid=electric_field_grid,
    )


def _nearest_grid_indices(grid: np.ndarray, values: np.ndarray) -> np.ndarray:
    """Return the index of the nearest coordinate in a monotone grid."""

    insertion = np.searchsorted(grid, values)
    insertion = np.clip(insertion, 1, len(grid) - 1)
    left = insertion - 1
    right = insertion

    choose_left = np.abs(values - grid[left]) <= np.abs(values - grid[right])
    return np.where(choose_left, left, right)
